### ISSUE TITLE
How do you open a connection to a custom receiver application?

### ISSUE THREAD

**Issue by jcrenfro** [thibauts/node-castv2#10]
I have a question about something in the readme. From the [Controlling Applications](https://github.com/thibauts/node-castv2#controlling-applications) section: 
> Another important field here is `transportId` as it is the destinationId to be used to communicate with the app. Note that the app being a receiver like any other you must issue it a `CONNECT` message through the `urn:x-cast:com.google.cast.tp.connection` procotol before being able to send messages.

I'm a little confused in how exactly to issue a `CONNECT` message when the application doesn't implement the `urn:x-cast:com.google.cast.tp.connection` procotol? Here is a snippet from my node app where I am trying to send messages to the custom receiver in a custom namespace. 

```
    var client = new CastClient();
    client.connect(service.addresses[0], function() {
        var connection = client.createChannel('sender-0', 'receiver-0', 'urn:x-cast:com.google.cast.tp.connection', 'JSON');
        var heartbeat  = client.createChannel('sender-0', 'receiver-0', 'urn:x-cast:com.google.cast.tp.heartbeat', 'JSON');
        var receiver   = client.createChannel('sender-0', 'receiver-0', 'urn:x-cast:com.google.cast.receiver', 'JSON');
        var myReceiver, launchRequestId;

        // establish virtual connection to the receiver
        connection.send({ type: 'CONNECT' });

        // start heartbeat
        setInterval(function() {
            //console.log("Sending heartbeat...");
            heartbeat.send({ type: 'PING' });
        }, 5000);

        receiver.send({ type: 'GET_APP_AVAILABILITY', appId: ['XXXXXX'], requestId: requestId++});
        receiver.send({ type: 'GET_STATUS', requestId: requestId++});

        receiver.on('message', function(data, broadcast) {

            if('GET_APP_AVAILABILITY' === data.responseType) {
                if ('APP_AVAILABLE' === data.availability['XXXXXX']) {
                    launchRequestId = requestId;
                    receiver.send({ type: 'LAUNCH', appId: 'XXXXXX', requestId: requestId++});
                }

            } else if ('RECEIVER_STATUS' === data.type) {
                if (data.requestId == launchRequestId) {
                    console.log('Handling LAUNCH response...');
                    var transportId;
                    data.status.applications.forEach(function(app) {
                        if ('XXXXXX' === app.appId) {
                            transportId = app.transportId;
                            console.log('Discovered transportId: ' + transportId);
                        }
                    });
                    if (transportId) {
                        myReceiver   = client.createChannel('sender-0', transportId, 'urn:x-cast:com.example.custom', 'JSON');
                        myReceiver.send({ type: 'CONNECT' });
                        setInterval(function() {
                            console.log("Sending message to custom receiver...");
                            myReceiver.send({type: 'PANG', requestId: requestId++});
                        }, 5000);
                        myReceiver.on('message', function(data, broadcast) {
                            console.log('\n\nGot message from receiver app!');
                            console.log(data);
                        });
                    }
                }
            }
        });
    });
```

The `RECEIVER_STATUS` response from the `LAUNCH` message looks like this: 

```
{ requestId: 2,
  status: 
   { applications: 
      [ { appId: 'XXXXXX',
          displayName: 'My Custom Receiver',
          namespaces: 
           [ { name: 'urn:x-cast:com.example.custom' },
             { name: 'urn:x-cast:com.google.cast.receiver' } ],
          sessionId: '4689EA8E-F47A-91EB-397B-0353534AD6FF',
          statusText: 'Ready to play',
          transportId: 'web-17' } ],
     volume: { level: 1, muted: false } },
  type: 'RECEIVER_STATUS' }
```
Notice that it does _not_ have the `urn:x-cast:com.google.cast.tp.connection` procotol. When I get this response, I am trying to open a new channel with the transportId `web-17` like this: `myReceiver   = client.createChannel('sender-0', transportId, 'urn:x-cast:com.example.custom', 'JSON');`

I am monitoring the console output and network traffic of the application (as shown in the [custom receiver docs](https://developers.google.com/cast/docs/custom_receiver#debugging)) and for the life of me I can't figure out how to send messages to and from the custom receiver. Any thoughts? How do you issue a `CONNECT` message to the receiver application?

**Comment by thibauts** [comment]
Requests to receiver apps through the `urn:x-cast:com.google.cast.tp.connection` protocol are handled by the receiver platform (the mother app) itself. You don't have to implement it in your receiver, it is available by default.

Before sending requests to your receiver app you have to connect to its `transportId` *from your "virtual" sending app*. What this means it the `CONNECT` request has to come from your sender app's `senderId`, and *not from your sender platform's `senderId`* (`sender-0`). And of course it has to be issued on the `urn:x-cast:com.google.cast.tp.connection` protocol (you're sending it on your custom protocol here).

This goes like this

```
if (transportId) {
  mySenderConnection = client.createChannel('client-xxxxx', transportId, 'urn:x-cast:com.google.cast.tp.connection', 'JSON');
  mySenderConnection.send({ type: 'CONNECT' });
  mySenderCustom = client.createChannel('client-xxxxx', transportId, 'urn:x-cast:com.example.custom', 'JSON');
  // ...
```

Here `client-xxxxx` is a randomly generated unique `senderId` for your app. It usually looks like `client-47382`.

Anyway, the protocol is quite involved and it will be much easier to implement your custom sender app with the objects provided by [node-castv2-client](https://github.com/thibauts/node-castv2-client). The module provides automatic connection and keepalive handling and takes care of `CONNECT` among many other things. Take a look at how the `DefaultMediaReceiver` is implemented or check [castv2-youtube](https://github.com/xat/castv2-youtube) which demonstrates how to build a custom receiver and implement custom protocol controllers in a very simple way.

**Comment by jcrenfro** [comment]
Oh, that makes a lot of sense! I will check out node-castv2-client in more detail and see if it would be easier to use. One quick question though, where do I get the `client-xxxxx` to create the channel from? I don't recall seeing a `senderId` in any of the messages I have been able to monitor... Is it a portion of the `sessionId`? Should I expect to see it in a `RECEIVER_STATUS` response message?

Thanks so much!

**Comment by jcrenfro** [comment]
Oh, you mean literally random... as in I need to generate it? I just found this method in the [node-castv2-client](https://github.com/thibauts/node-castv2-client) project:
```
function randomSenderId() {
  return 'client-' + Math.floor(Math.random() * 10e5);
}
```

I'll give it a try like that, thanks again!

**Comment by thibauts** [comment]
I was about to send you the link :). That's it ! Good luck !
