### ISSUE TITLE
Getting information about a playing YouTube Video

### ISSUE THREAD

**Issue by schokocappucino** [thibauts/node-castv2#13]
Is it possible to get information about a playing YouTube video?
I can see that YouTube is running using the GET_STATUS command in the receiver channel and I tried opening the `urn:x-cast:com.google.cast.media` and `urn:x-cast:com.google.youtube.mdx` channels, but I don't get responses after sending GET_STATUS in them.

**Comment by thibauts** [comment]
Hmm. You should ask @xat of [castv2-youtube](https://github.com/xat/castv2-youtube) or check the repository code.

**Comment by schokocappucino** [comment]
That only works if I started the video using castv2-youtube, not from the Chrome extension or my phone.

**Comment by thibauts** [comment]
My first guess would be they use the old protocol / app so status updates don't get broadcast on the castv2 channel. But I may be wrong.

**Comment by schokocappucino** [comment]
You were right, it works using castv2-youtube. I overlooked client.getSessions and tried to create an Application using the sessionId as string at first.

```js
var client = new Client();
	client.connect(host, function() {
		console.log('connected, launching app ...');
		
		client.getSessions(function (err, sessions) {
			console.log(sessions);
			
			client.join(sessions[0], Youtube, function(err, player) {
				player.getStatus(function (err, data) {
					console.log(data);
				});
			});
		});
	});
```

**Comment by thibauts** [comment]
Great :) thanks for posting the example code. Might help others
