### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by Ten10** [thibauts/node-castv2#15]
Hello,
I'm using popcorn time which uses your module to cast to chromecast.

I opened the dev tools during casting since the application was stuck.

It seems like the ps member is null.

I attached a screenshot.

![image](https://cloud.githubusercontent.com/assets/3170167/8090525/22f1b3e4-0fb7-11e5-874c-2293c33655e3.png)

**Comment by thibauts** [comment]
Sure. The code in popcorntime using `castv2-client` should handle `error` events properly and reconnect as needed.

This error surfaces only if you don't handle client's lifetime events. Thus I won't silence it or "resolve" it in any way here.
