### ISSUE TITLE
Casting does not work.

### ISSUE THREAD

**Issue by Ten10** [thibauts/node-castv2#16]
It seems like the problem is originating from the castv2 module when connecting to the chromecast device.

In request-response.js onmessage function.

The response.type is LAUNCH_ERROR which is not translated into an error and is passed to the callback.

Attached is a screenshot.
![image](https://cloud.githubusercontent.com/assets/3170167/8126677/664fe7ee-10f9-11e5-8710-7c870b7f2ab5.png)

**Comment by thibauts** [comment]
`LAUNCH_ERROR` should be translated to an error [here](https://github.com/thibauts/node-castv2-client/blob/master/lib/controllers/receiver.js#L51) with the error reason attached.

Depending on the results you get, you may want to file an issue on the `chromecast-js` repo.

**Comment by Ten10** [comment]
It seems like the launch error handling was added on 5 of march.
I guess they aren't using the updated code.

I'll let them know so they can update it to the current one.
