### ISSUE TITLE
Catching Device Reboots

### ISSUE THREAD

**Issue by issackelly** [thibauts/node-castv2#17]
I'd like to use this to catch devices that reboot or fall off and rejoin the network. 

I'm working from the example code, and reading your docs, it seems like it might throw a connection closed event. When I reboot the chromecast via the on-device button or the official chromecast app, I get

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: read ECONNRESET
        at exports._errnoException (util.js:746:11)
        at TCP.onread (net.js:559:26)

Not getting a full traceback, and not being familiar with node's network stack or this code, I'm a little lost as to where I should be catching this error.

**Comment by thibauts** [comment]
You should be able to catch the connection reset event in an error event handler on the client like this :
```javascript
client.on('error', function(err) {
  //
});
```
