### ISSUE TITLE
Receiver TLS handshaking

### ISSUE THREAD

**Issue by jeffgriffin** [thibauts/node-castv2#25]
I'm using your Server with the official music app, [like this](https://gist.github.com/jeffgriffin/bbf9439b634f2f1af69c).  The odd thing is, the client sends a FIN right after my Server Hello Done.  I would assume that it just doesn't like my self-signed cert, but the information you have here suggests that you've progressed to the point of exchanging protobuf messages.  I've tried generating a larger key (official Chromecast Audio appears to use 2048 bits).  I noticed that the official platform sends Server Hello/Cert/Key Exchange/Server Hello Done all in one record, while node tls sends individual records, but it's starting to feel like I'm in the weeds.  Thoughts?

**Comment by thibauts** [comment]
I fear this isn't possible without the correct certificate.
