### ISSUE TITLE
Update protobufjs

### ISSUE THREAD

**Issue by amilajack** [thibauts/node-castv2#30]
`node-castv2` is using an [old version of protobufjs](https://david-dm.org/thibauts/node-castv2), which has [issues with webpack](https://github.com/dcodeIO/protobuf.js/issues/339). Updating to the latest version of `protobufjs` could resolve this issue.

**Comment by amilajack** [comment]
I've made a PR for this: https://github.com/thibauts/node-castv2/pull/31

**Comment by amilajack** [comment]
I've just noticed that the updated protobufjs version doesnt work with this module due to api changes. Could you try updating this module to be compatible with the new api changes?

**Comment by thibauts** [comment]
Please do or revert your changes as soon as possible so I can republish
soon. Thanks

Le 18 août 2016 12:41 AM, "Amila Welihinda" <notifications@github.com> a
écrit :

**Comment by thibauts** [comment]
Pretty please, never do this again. Many people depend on this package. We can't afford to break things on minor versions like that. Thanks.

**Comment by amilajack** [comment]
Sorry about that. Usually I rely on tests to check if things would break but writing tests for this kind of module would be difficult. Wont do it again.
