### ISSUE TITLE
Question: What are the build steps for this project?

### ISSUE THREAD

**Issue by amilajack** [thibauts/node-castv2#32]
@thibauts what steps do you follow before publishing this module?

**Comment by thibauts** [comment]
There is no build process. What would you see it build ?

**Comment by amilajack** [comment]
I saw that this project has a makefile. I was wondering if that was necessary to build it.

**Comment by thibauts** [comment]
Oh, right ! I mostly used this as a reference documenting how some files were built. The protobuf desc file is already included, and the cert stuff was to make server testing easier in the early stages.

**Comment by amilajack** [comment]
Got it. So I dont need to run the makefile to build/publish?

**Comment by thibauts** [comment]
Nope, it's fine to only up the version and publish

**Comment by amilajack** [comment]
Got it. Thanks!
