### ISSUE TITLE
node-castv3?

### ISSUE THREAD

**Issue by amilajack** [thibauts/node-castv2#37]
Will there be an implementation for the castv3 protocol?

**Comment by thibauts** [comment]
If someone works on it, probably !

I've never heard about it though. Could you drop a link to more information about it ?

**Comment by amilajack** [comment]
https://developers.google.com/cast/docs/release-notes#june-27-2016

**Comment by thibauts** [comment]
> This release of Cast SDK v3.0.0 is an upgrade of the Cast Sender v2 APIs for Android and iOS.

As I understand it, v3 is the SDK version. The underlying protocol is still v2 and most probably hasn't changed.
