### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by JustMeDaFaq** [thibauts/node-castv2#38]
Hi,
is typescript support planned?

Tried it like that:

```
//make sure require gets defined like this:
declare var require:(moduleId:string) => any;
//trying castv2
var Client  = require('castv2-client').Client;
```

But im getting following error
http://localhost:8100/node_modules/castv2/lib/cast_channel.proto 404 (Not Found)

Using ionic2 / angular 2

**Comment by thibauts** [comment]
This module is meant to be used server-side. You won't make it work client-side...
