### ISSUE TITLE
Sending messages to specific app (documentation / how to)

### ISSUE THREAD

**Issue by taboca** [thibauts/node-castv2#40]
I read your project documentation and it helped me to further advance and send a message to my specific web app — https://github.com/taboca/castv2-sender-web

The core of my changes went here 

```
 // display receiver status updates
    receiver.on('message', function(data, broadcast) {
      if(data.type = 'RECEIVER_STATUS') {

        var transportIdSession='';
        for(k in data.status.applications) {
                var appData = data.status.applications[k];
                if(appData.appId == 'A7BD302D') {
                        transportIdSession = appData.transportId;
                        console.log('transport id = ' + transportIdSession);
                }
        }

        var connection = client.createChannel('sender-0', transportIdSession, 'urn:x-cast:com.google.cast.tp.connection', 'JSON');
        connection.send({ type: 'CONNECT' });
        var app   = client.createChannel('sender-0', transportIdSession , 'urn:x-cast:com.telasocial.tagvisor', 'JSON');
        app.send({ url: 'http://www.telasocial.com',force: false, reload: true, reload_time: 50000 });

      }
    });
```

It was able to push an url to my server app, above appId. I wonder if such extended example could be added to your documentation.

**Comment by taboca** [comment]
Of course, it does not have to be my whitelisted app. One thing to notice, in the above code, is that my init code is situated under the message listener, so I believe that I might be loading my app 3 times in a row.

**Comment by taboca** [comment]
If I understand correctly, I believe I have patched the multiple loads https://github.com/taboca/castv2-sender-web/commit/6275eaf31d2b4609277b9ced8eb7b2d795715329

**Comment by thibauts** [comment]
I suggest you check https://github.com/thibauts/node-castv2-client which provides a much simpler interface to creating custom senders. You won't have to deal with the details. Check out the DefaultMediaReceiver app.
