### ISSUE TITLE
Question: How to play Youtube or Netflix video?

### ISSUE THREAD

**Issue by reggi** [thibauts/node-castv2#42]
Hey! Loving this library! Thanks for your work.

I'm trying to figure out how to set a specific video to play from Youtube or Netflix.  Any assistance would be greatly appreciated. Thanks!

Also a list of all the different types / actions available (play, pause, stop, etc) would be nice. Or a general way to view all network events on the cast.

**Comment by Ivshti** [comment]
You can check this out for youtube: https://github.com/xat/castv2-youtube
As for Netflix, I'm not sure it's really possible /without breaking ToS/. Netflix has it's own receiver and i'm presuming it's not publically documented
